using STS.Mfg.Application.Contracts.Inventory;

namespace STS.Mfg.Application.Contracts.ServiceManagement;

public sealed record ServiceManagementFilter(
    int Page = 1,
    int PageSize = 25,
    string? Search = null,
    string? Status = null,
    DateTimeOffset? DateFrom = null,
    DateTimeOffset? DateTo = null,
    long? CompanyId = null,
    long? BranchId = null,
    long? CustomerId = null,
    long? InstalledAssetId = null,
    long? ServiceTicketId = null) : QueryFilter(Page, PageSize, Search, Status, DateFrom, DateTo);

public sealed record InstalledAssetDto(
    long Id,
    long? CompanyId,
    long? BranchId,
    string AssetNo,
    long CustomerId,
    long? CustomerSiteId,
    long? CustomerContactId,
    long ItemId,
    long? ItemRevisionId,
    long? SerialId,
    string? SerialNo,
    long? LotId,
    long? PcidId,
    long? SourceSalesOrderId,
    long? SourceSalesOrderLineId,
    long? SourceDispatchId,
    long? SourceDispatchLineId,
    long? SourceInvoiceId,
    string? SourceDocumentType,
    string? SourceDocumentNo,
    int? SourceDocumentRevisionNo,
    DateOnly InstallationDate,
    DateOnly? CommissioningDate,
    DateOnly? WarrantyStartDate,
    DateOnly? WarrantyEndDate,
    long? ServiceContractId,
    string Status,
    string? LocationSnapshot,
    string? Remarks,
    bool LegacySourceIncomplete);

public sealed record InstalledAssetUpsertRequest(
    long CompanyId,
    long? BranchId,
    string AssetNo,
    long CustomerId,
    long? CustomerSiteId,
    long? CustomerContactId,
    long ItemId,
    long? ItemRevisionId,
    long? SerialId,
    string? SerialNo,
    long? LotId,
    long? PcidId,
    long? SourceSalesOrderId,
    long? SourceSalesOrderLineId,
    long? SourceDispatchId,
    long? SourceDispatchLineId,
    long? SourceInvoiceId,
    string? SourceDocumentType,
    string? SourceDocumentNo,
    int? SourceDocumentRevisionNo,
    DateOnly InstallationDate,
    DateOnly? CommissioningDate,
    DateOnly? WarrantyStartDate,
    DateOnly? WarrantyEndDate,
    long? ServiceContractId,
    string Status,
    string? LocationSnapshot,
    string? Remarks,
    bool LegacySourceIncomplete);

public sealed record WarrantyPolicyDto(
    long Id,
    long? CompanyId,
    string PolicyCode,
    string PolicyName,
    long? ItemId,
    long? ItemGroupId,
    long? CustomerGroupId,
    int DurationDays,
    string StartTrigger,
    bool CoversParts,
    bool CoversLabor,
    bool CoversOnsite,
    bool CoversReplacement,
    string? Exclusions,
    decimal? ClaimLimitAmount,
    string Status);

public sealed record WarrantyPolicyUpsertRequest(
    long? CompanyId,
    string PolicyCode,
    string PolicyName,
    long? ItemId,
    long? ItemGroupId,
    long? CustomerGroupId,
    int DurationDays,
    string StartTrigger,
    bool CoversParts,
    bool CoversLabor,
    bool CoversOnsite,
    bool CoversReplacement,
    string? Exclusions,
    decimal? ClaimLimitAmount,
    string Status);

public sealed record ServiceContractDto(
    long Id,
    long? CompanyId,
    long? BranchId,
    string ContractNo,
    long CustomerId,
    long? InstalledAssetId,
    DateOnly StartDate,
    DateOnly EndDate,
    DateOnly? RenewalDate,
    string CoverageSummary,
    int? VisitFrequencyDays,
    string? PreventiveScheduleJson,
    int? SlaResponseHours,
    long? BillingTermsId,
    decimal? ContractValueAmount,
    long? TaxCodeId,
    decimal? TaxRateSnapshot,
    string Status,
    int VersionNo,
    long? PriorContractId);

public sealed record ServiceContractUpsertRequest(
    long CompanyId,
    long? BranchId,
    string ContractNo,
    long CustomerId,
    long? InstalledAssetId,
    DateOnly StartDate,
    DateOnly EndDate,
    DateOnly? RenewalDate,
    string CoverageSummary,
    int? VisitFrequencyDays,
    string? PreventiveScheduleJson,
    int? SlaResponseHours,
    long? BillingTermsId,
    decimal? ContractValueAmount,
    long? TaxCodeId,
    decimal? TaxRateSnapshot,
    string Status,
    int VersionNo,
    long? PriorContractId);

public sealed record ServiceEntitlementDto(
    string EntitlementType,
    string Source,
    long? WarrantyPolicyId,
    long? ServiceContractId,
    DateOnly? StartDate,
    DateOnly? EndDate,
    DateOnly CheckedOn,
    string SnapshotJson);

public sealed record ServiceTicketDto(
    long Id,
    long? CompanyId,
    long? BranchId,
    string TicketNo,
    long CustomerId,
    long? ContactId,
    long? InstalledAssetId,
    long? ItemId,
    string? SerialNo,
    string IssueCategory,
    string IssueDescription,
    string Priority,
    string Severity,
    string Channel,
    long? SourceIntegrationMessageId,
    string EntitlementType,
    string? EntitlementSource,
    long? EntitlementPolicyId,
    long? EntitlementContractId,
    string? EntitlementSnapshotJson,
    DateOnly? EntitlementCheckedOn,
    long? AssignedOwnerUserId,
    long? AssignedTeamId,
    DateTimeOffset? TargetResponseOn,
    DateTimeOffset? TargetResolutionOn,
    string Status,
    string? InternalRemarks,
    string? CustomerFacingRemarks,
    long? SourceSalesOrderId,
    long? SourceDispatchId,
    long? SourceInvoiceId,
    string? AssetSnapshotJson,
    string? ReopenReason,
    DateTimeOffset? ClosedOn,
    long? ClosedByUserId,
    string? ClosureReason);

public sealed record ServiceTicketUpsertRequest(
    long CompanyId,
    long? BranchId,
    string TicketNo,
    long CustomerId,
    long? ContactId,
    long? InstalledAssetId,
    long? ItemId,
    string? SerialNo,
    string IssueCategory,
    string IssueDescription,
    string Priority,
    string Severity,
    string Channel,
    long? SourceIntegrationMessageId,
    long? AssignedOwnerUserId,
    long? AssignedTeamId,
    DateTimeOffset? TargetResponseOn,
    DateTimeOffset? TargetResolutionOn,
    string Status,
    string? InternalRemarks,
    string? CustomerFacingRemarks,
    long? SourceSalesOrderId,
    long? SourceDispatchId,
    long? SourceInvoiceId);

public sealed record ServiceTicketAssignmentRequest(
    long? AssignedOwnerUserId,
    long? AssignedTeamId,
    DateTimeOffset? TargetResponseOn,
    DateTimeOffset? TargetResolutionOn);

public sealed record ServiceTicketStatusRequest(string Status, string? Reason);

public sealed record ServiceVisitDto(
    long Id,
    long? CompanyId,
    long? BranchId,
    long ServiceTicketId,
    long? TechnicianUserId,
    long? TeamId,
    DateTimeOffset? ScheduledStartOn,
    DateTimeOffset? ScheduledEndOn,
    string? VisitAddressSnapshot,
    DateTimeOffset? TravelStartedOn,
    DateTimeOffset? WorkStartedOn,
    DateTimeOffset? WorkEndedOn,
    string? WorkPerformed,
    string? Diagnosis,
    string? Resolution,
    string? CustomerSignoffName,
    DateTimeOffset? CustomerSignoffOn,
    long? EvidenceAttachmentId,
    long? PhotoEvidenceId,
    string Status,
    string? Remarks);

public sealed record ServiceVisitUpsertRequest(
    long CompanyId,
    long? BranchId,
    long ServiceTicketId,
    long? TechnicianUserId,
    long? TeamId,
    DateTimeOffset? ScheduledStartOn,
    DateTimeOffset? ScheduledEndOn,
    string? VisitAddressSnapshot,
    DateTimeOffset? TravelStartedOn,
    DateTimeOffset? WorkStartedOn,
    DateTimeOffset? WorkEndedOn,
    string? WorkPerformed,
    string? Diagnosis,
    string? Resolution,
    string? CustomerSignoffName,
    DateTimeOffset? CustomerSignoffOn,
    long? EvidenceAttachmentId,
    long? PhotoEvidenceId,
    string Status,
    string? Remarks);

public sealed record ServiceSpareMovementDto(
    long Id,
    long? CompanyId,
    long? BranchId,
    string MovementNo,
    string MovementType,
    long ServiceTicketId,
    long? ServiceVisitId,
    long ItemId,
    long? ItemRevisionId,
    long WarehouseId,
    long? BinId,
    long? LotId,
    long? SerialId,
    string? SerialNo,
    long? PcidId,
    decimal Quantity,
    string InventoryState,
    long? StockTransactionId,
    long? ReplacementInstalledAssetId,
    long? DefectiveInstalledAssetId,
    string Status,
    string? ReasonCode,
    string? Remarks);

public sealed record ServiceSpareMovementRequest(
    long CompanyId,
    long? BranchId,
    string MovementNo,
    long ServiceTicketId,
    long? ServiceVisitId,
    long ItemId,
    long? ItemRevisionId,
    long WarehouseId,
    long? BinId,
    long? LotId,
    long? SerialId,
    string? SerialNo,
    long? PcidId,
    decimal Quantity,
    string InventoryState,
    string? ReasonCode,
    string? Remarks,
    long? ReplacementInstalledAssetId,
    long? DefectiveInstalledAssetId,
    DateOnly PostingDate,
    string? SourceDocumentNo);

public sealed record WarrantyClaimDto(
    long Id,
    long? CompanyId,
    long? BranchId,
    string ClaimNo,
    long ServiceTicketId,
    long? InstalledAssetId,
    long CustomerId,
    long? ItemId,
    string? SerialNo,
    string ClaimType,
    string EntitlementType,
    string? EntitlementSnapshotJson,
    string ApprovalStatus,
    string? Disposition,
    long? ReplacementAssetId,
    string? CostDecision,
    string? RejectionReason,
    string? OverrideReason,
    string Status);

public sealed record WarrantyClaimUpsertRequest(
    long CompanyId,
    long? BranchId,
    string ClaimNo,
    long ServiceTicketId,
    long? InstalledAssetId,
    long CustomerId,
    long? ItemId,
    string? SerialNo,
    string ClaimType,
    string EntitlementType,
    string? EntitlementSnapshotJson,
    string ApprovalStatus,
    string? Disposition,
    long? ReplacementAssetId,
    string? CostDecision,
    string? RejectionReason,
    string? OverrideReason,
    string Status);

public sealed record WarrantyClaimDecisionRequest(
    string ApprovalStatus,
    string? Disposition,
    string? RejectionReason,
    string? OverrideReason,
    long? ReplacementAssetId);

public sealed record ServiceChargeDto(
    long Id,
    long? CompanyId,
    long? BranchId,
    string ChargeNo,
    long ServiceTicketId,
    long CustomerId,
    long? CurrencyId,
    decimal LaborAmount,
    decimal PartsAmount,
    decimal TravelAmount,
    decimal OtherAmount,
    decimal DiscountAmount,
    long? TaxCodeId,
    decimal? TaxRateSnapshot,
    decimal TaxAmount,
    decimal TotalAmount,
    string BillableStatus,
    string? NonBillableReason,
    long? ArInvoiceId,
    string Status,
    string SnapshotJson);

public sealed record ServiceChargeUpsertRequest(
    long CompanyId,
    long? BranchId,
    string ChargeNo,
    long ServiceTicketId,
    long CustomerId,
    long? CurrencyId,
    decimal LaborAmount,
    decimal PartsAmount,
    decimal TravelAmount,
    decimal OtherAmount,
    decimal DiscountAmount,
    long? TaxCodeId,
    decimal? TaxRateSnapshot,
    decimal TaxAmount,
    decimal TotalAmount,
    string BillableStatus,
    string? NonBillableReason,
    long? ArInvoiceId,
    string Status,
    string SnapshotJson);

public sealed record ServiceDashboardDto(
    int OpenTickets,
    int WaitingForParts,
    int ActiveContracts,
    int WarrantyClaimsPending,
    int InvoiceReadyCharges,
    IReadOnlyCollection<string> DisabledActionReasons);

public sealed record ServiceSparePostResultDto(ServiceSpareMovementDto Movement, IReadOnlyCollection<StockTransactionDto> StockTransactions);
